// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJlw0Nepp-iRKHxlsgvHYw7Lje0JHNTqA',
    appId: '1:731808727071:web:cdcb084d246b9bde3c952a',
    messagingSenderId: '731808727071',
    projectId: 'nmsapp-beeec',
    authDomain: 'nmsapp-beeec.firebaseapp.com',
    storageBucket: 'nmsapp-beeec.appspot.com',
    measurementId: 'G-R8XERQFPS9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJsCGWPN5xzUHf6bGA1LUr-vDUEtBfnlA',
    appId: '1:731808727071:android:0e187a4ed61a65043c952a',
    messagingSenderId: '731808727071',
    projectId: 'nmsapp-beeec',
    storageBucket: 'nmsapp-beeec.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAv7_CHYEyl5JSHdFZcIPq9CvrjsAfahdI',
    appId: '1:731808727071:ios:d63526c8fe4825ef3c952a',
    messagingSenderId: '731808727071',
    projectId: 'nmsapp-beeec',
    storageBucket: 'nmsapp-beeec.appspot.com',
    iosClientId: '731808727071-fjp53e675kjd0c4sn6a77ecqjistg2ro.apps.googleusercontent.com',
    iosBundleId: 'com.example.nmsInit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAv7_CHYEyl5JSHdFZcIPq9CvrjsAfahdI',
    appId: '1:731808727071:ios:d63526c8fe4825ef3c952a',
    messagingSenderId: '731808727071',
    projectId: 'nmsapp-beeec',
    storageBucket: 'nmsapp-beeec.appspot.com',
    iosClientId: '731808727071-fjp53e675kjd0c4sn6a77ecqjistg2ro.apps.googleusercontent.com',
    iosBundleId: 'com.example.nmsInit',
  );
}
